trigger:
- none

parameters:
  - name: temp_deploy
    default:
pool:
  vmImage: windows-latest

stages:
 - stage: build
   jobs:
   - job: build_job_name
     steps:
      - script: |
          echo 'stage build Completed !'
          echo "Build.ArtifactStagingDirectory: $(Build.ArtifactStagingDirectory)"
          echo "Build.BuildId: $(Build.BuildId)"
          echo "Build.BuildNumber: $(Build.BuildNumber)"
          echo "System.JobId: $(System.JobId)"
          echo "System.JobName: $(System.JobName)"
          echo "System.DefinitionId: $(System.DefinitionId)"
        displayName: 'stage build Completed'

 - stage: deploy
   jobs:
    - deployment: Deploy
      environment: Test
      displayName: Deploy resources
      strategy:                  
        runOnce:
          deploy:
            steps:
              - task: PowerShell@1    
                displayName: stage deploy Completed
                inputs:
                  scriptType: inlineScript
                  inlineScript: > 
                    ech 'stage deploy started !'
                    echo "Build.ArtifactStagingDirectory: $(Build.ArtifactStagingDirectory)"
                    echo "Build.BuildId: $(Build.BuildId)"
                    echo "Build.BuildNumber: $(Build.BuildNumber)"
                    echo "System.JobId: $(System.JobId)"
                    echo "System.JobName: $(System.JobName)"
                    echo "System.DefinitionId: $(System.DefinitionId)"
                    echo '-- Version 2.0 --'
                    echo 'stage deploy completed !'
          on:
            failure:
              steps:        
              - task: PowerShell@2
                inputs:
                  failOnStderr: true
                  targetType: 'inline'
                  script: |
                    New-AzResourceGroupDeployment -Name ExampleDeployment02 `-ResourceGroupName $resourceGroupName `-TemplateFile c:\MyTemplates\azuredeploy.json `-RollbackToLastDeployment